### ISSUE TITLE
(Help needed) Running tRPC and React app on server

### ISSUE THREAD

**Issue by vildantursic** [Perfect7M/taurine#8]
Hi,
I have a question regarding architecture.
After pulling code I updated tRPC to the latest version and updated everything accordingly.

Now when I do `tauri dev` build for desktop app (macos in my case) it works just fine, tRPC is spinning on port 3000 and app is open on port 1420 the comunicate.
This way web app also works. But as soon as I kill `tauri dev` and try running tRPC separately by just running server:watch or manually trying to run index.ts or any other way backend (trpc) is just not up I can't reach it on port 3000 on separately run React with `vite dev`.
`watch-server.js` completes build and everything seams fine but tRPC is not available at port 3000
Am I missing something here

Thank you in advance

**Comment by marcincodes** [comment]
Hi @vildantursic, `watch-server.js` script is watching `server/*` directory and rebuilding package when something change. That's why you need to run `tauri dev` to run package (and the server in it)

You might try: https://github.com/esbuild-kit/tsx
You should run it like:
```bash
npx tsx ./server/index.ts
```

**Comment by vildantursic** [comment]
Thank you, that works like a charm!
I made something similar with `tsc` building it and running then with node, but I like this single line approach with `tsx` more
Much appreciated 😊
